### ISSUE TITLE
pagination of search result

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/pixl-server-storage#4]
Not really an issue, just some thoughts. So in Cronicle,  events that run every few minutes would have tons of history pages. So it might be a challenge to locate jobs that failed. Thinking of a method of getting last N errors for the event or paginated error page. 

From the discussion on cronicle issues, I got an impression that pagination will be implemented in v2, wondering how you are going to do that?

Sounds like this is the only "search" function to retrieve multiple items from the list. I guess that would work for the last N search, but not for the pagination.

```js
storage.listFindEach( 'list1', { gender: 'male' }, function(item, idx, callback) {
	// do something with item, then fire callback
	callback();
}, 
function(err) {
	if (err) throw err;
	// all matched items iterated over
} );
```

Some other thoughts on  listFindEach:
 - filtering via object is not good if you need to filter values grater/smaller that some number or date. Maybe filter can be passed via function  (same way as JS array's filter method)
 - Is it possible to search (efficiently) items starting from some offset?  This could be useful for pagination. E.g. you can search for the first N items matching your filter (from the beginning). Then storage can return an offset of the next matching item (along with item collection). Then this offset can be used for the next search ("page").

**Comment by jhuckaby** [comment]
Yup, for Orchestra I am abandoning storage "lists" entirely, as they don't work well for searching.  I am using my "Unbase" library:

https://github.com/jhuckaby/pixl-server-unbase

It's sort of like a database, it has indexes, and it can easily perform index-based searches for things like "jobs for specific event, but exited with error" very quickly.

I use this library at work for several large scale applications (including a chat app that has over 100M rows), not to mention our entire CI/CD system, and it works great.  It has been battle tested.
